# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 05:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relate_select', '0002_auto_20171206_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specie_name', models.CharField(max_length=100)),
                ('specie_desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='track',
            name='album',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Track',
        ),
        migrations.AddField(
            model_name='sources',
            name='source_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='relate_select.Species'),
        ),
        migrations.AddField(
            model_name='process',
            name='process_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process', to='relate_select.Sources'),
        ),
        migrations.AlterUniqueTogether(
            name='sources',
            unique_together=set([('source_name', 'source_desc')]),
        ),
    ]
