# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relate_select', '0003_auto_20171206_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='source_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='source', to='relate_select.Sources'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sources',
            name='specie_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='specie', to='relate_select.Species'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='process',
            name='process_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sources',
            name='source_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='sources',
            unique_together=set([]),
        ),
    ]
