# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-06 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relate_select', '0006_auto_20171206_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sources',
            name='source_desc',
        ),
        migrations.RemoveField(
            model_name='species',
            name='specie_desc',
        ),
        migrations.AlterField(
            model_name='species',
            name='specie_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
