# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-12 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relate_select', '0011_auto_20171206_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sources',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='species',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
