# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-12 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relate_select', '0012_auto_20171212_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='sources',
            name='is_active',
        ),
    ]
