# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-27 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relate_select', '0015_auto_20180126_1127'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='process',
            unique_together=set([]),
        ),
    ]
