# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relate_select', '0016_auto_20180228_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='process',
            name='document',
        ),
        migrations.RemoveField(
            model_name='process',
            name='gse_id',
        ),
        migrations.RemoveField(
            model_name='process',
            name='gsm_id',
        ),
        migrations.AddField(
            model_name='process',
            name='citation',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='process',
            name='gse',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='process',
            name='gsm',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='process',
            name='pmid',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='process',
            name='srr',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='process',
            name='submit_date',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='process',
            name='tissue',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='process',
            name='oganization',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='process',
            name='process_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
