# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-07 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relate_select', '0017_auto_20180306_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='GsmDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bw_file_size', models.CharField(default='', max_length=20)),
                ('qc_trim_rate', models.CharField(default='', max_length=5)),
                ('qc_mapping_rate', models.CharField(default='', max_length=5)),
                ('qc_unique_mapping_rate', models.CharField(default='', max_length=5)),
                ('qc_sequence_length', models.CharField(default='', max_length=20)),
                ('qc_gc_rate', models.CharField(default='', max_length=5)),
                ('qc_file_size', models.CharField(default='', max_length=20)),
                ('tpm_0', models.IntegerField(default=0)),
                ('tpm_0_1', models.IntegerField(default=0)),
                ('tpm_1_10', models.IntegerField(default=0)),
                ('tpm_10_100', models.IntegerField(default=0)),
                ('tpm_100_1000', models.IntegerField(default=0)),
                ('tpm_1000_10000', models.IntegerField(default=0)),
                ('tpm_10000_100000', models.IntegerField(default=0)),
                ('tpm_above_100000', models.IntegerField(default=0)),
                ('tpm_top_5', models.CharField(default='', max_length=300)),
                ('tpm_file_size', models.CharField(default='', max_length=20)),
                ('nascent_number', models.IntegerField(default=0)),
                ('nascent_intra', models.IntegerField(default=0)),
                ('nascent_inter', models.IntegerField(default=0)),
                ('nascent_below_100', models.IntegerField(default=0)),
                ('nascent_100_1000', models.IntegerField(default=0)),
                ('nascent_1000_5000', models.IntegerField(default=0)),
                ('nascent_5000_10000', models.IntegerField(default=0)),
                ('nascent_10000_50000', models.IntegerField(default=0)),
                ('nascent_50000_100000', models.IntegerField(default=0)),
                ('nascent_over_100000', models.IntegerField(default=0)),
                ('nascent_file_size', models.CharField(default='', max_length=20)),
                ('enhancer_number', models.IntegerField(default=0)),
                ('enhancer_below_100', models.IntegerField(default=0)),
                ('enhancer_100_500', models.IntegerField(default=0)),
                ('enhancer_500_1000', models.IntegerField(default=0)),
                ('enhancer_1000_5000', models.IntegerField(default=0)),
                ('enhancer_5000_9000', models.IntegerField(default=0)),
                ('enhancer_length_total', models.IntegerField(default=0)),
                ('enhancer_file_size', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
